#include "GameEditor/UI/RuntimeDebugPrimitivesSection.h"
#include "GameRuntime/App.h"
#include "GUI/Declarative/Build.h"
#include "GUI/Widgets/Controls/CheckBox.h"
#include "GUI/Widgets/Controls/Text.h"
#include "Render3D/RenderDeviceState.h"
#include "Render3D/Services/DebugRenderSystem.h"
#include <format>
namespace ya { namespace { std::shared_ptr<UICheckBox> box(const char* key,const char* label){ auto b=std::make_shared<UICheckBox>(key); auto t=std::make_shared<UIText>(std::string(key)+"Label"); t->setText(label); b->addDetachedChild(t); return b; } } RuntimeDebugPrimitivesSection::RuntimeDebugPrimitivesSection(std::string name):UICompoundWidget(std::move(name),"panel"){} void RuntimeDebugPrimitivesSection::construct(){ _counts=ui::text("RuntimeDebugCounts").share(); _enabled=box("RuntimeDebugEnabled","Enabled"); _depth=box("RuntimeDebugDepth","Depth Test"); _lines=box("RuntimeDebugLines","Draw Lines"); _shapes=box("RuntimeDebugShapes","Draw Shapes"); auto rows=ui::column("RuntimeDebugRows").setSpacing(3.0f).child(ui::text("RuntimeDebugHeader").setText("Debug Primitives").setStyleKey("text.header")).child(_enabled).child(_depth).child(_lines).child(_shapes).child(_counts); addDetachedChild(rows.release()); _enabled->_onChanged=[this](bool){ if(auto* app=App::get()) if(auto* r=app->getRenderServices().getDeviceState()) { auto s=r->getDebugRenderSystem().buildSettingsSnapshot(); s.bEnabled=_enabled->isChecked(); r->getDebugRenderSystem().requestSettings(s); } }; _depth->_onChanged=[this](bool){ if(auto* app=App::get()) if(auto* r=app->getRenderServices().getDeviceState()) { auto s=r->getDebugRenderSystem().buildSettingsSnapshot(); s.bDepthTest=_depth->isChecked(); r->getDebugRenderSystem().requestSettings(s); } }; _lines->_onChanged=[this](bool){ if(auto* app=App::get()) if(auto* r=app->getRenderServices().getDeviceState()) { auto s=r->getDebugRenderSystem().buildSettingsSnapshot(); s.bDrawLines=_lines->isChecked(); r->getDebugRenderSystem().requestSettings(s); } }; _shapes->_onChanged=[this](bool){ if(auto* app=App::get()) if(auto* r=app->getRenderServices().getDeviceState()) { auto s=r->getDebugRenderSystem().buildSettingsSnapshot(); s.bDrawShapes=_shapes->isChecked(); r->getDebugRenderSystem().requestSettings(s); } }; } void RuntimeDebugPrimitivesSection::sync(const App* app){ if(!_counts||!_enabled||!_depth||!_lines||!_shapes||!app)return; auto* r=app->getRenderServices().getDeviceState(); if(!r){_counts->setText("Debug primitives unavailable");return;} auto s=r->getDebugRenderSystem().buildSettingsSnapshot(); _enabled->setChecked(s.bEnabled); _depth->setChecked(s.bDepthTest); _lines->setChecked(s.bDrawLines); _shapes->setChecked(s.bDrawShapes); _counts->setText(std::format("Pending {} lines / {} shapes | Frame {} / {} | Immediate {} / {}",s.pendingLineCount,s.pendingShapeCount,s.frameLineCount,s.frameShapeCount,s.immediateLineCount,s.immediateShapeCount)); } }
