#include "GameEditor/UI/RuntimeRenderTargetSection.h"
#include "GameRuntime/App.h"
#include "GUI/Declarative/Build.h"
#include "GUI/Widgets/Controls/Text.h"
#include "Render3D/RenderRuntime.h"
#include "Render3D/Common/RenderTargetCatalog.h"
#include "RHI/RenderDefines.h"
#include <format>
namespace ya { namespace { const char* ownerLabel(RenderTargetCatalog::Entry::EOwner owner) { switch(owner) { case RenderTargetCatalog::Entry::EOwner::Presentation:return "Presentation"; case RenderTargetCatalog::Entry::EOwner::ForwardViewport:return "Forward Viewport"; case RenderTargetCatalog::Entry::EOwner::ForwardShadow:return "Forward Shadow"; case RenderTargetCatalog::Entry::EOwner::DeferredGBuffer:return "Deferred GBuffer"; case RenderTargetCatalog::Entry::EOwner::DeferredViewport:return "Deferred Viewport"; case RenderTargetCatalog::Entry::EOwner::DeferredShadow:return "Deferred Shadow"; } return "Unknown"; } } RuntimeRenderTargetSection::RuntimeRenderTargetSection(std::string name):UICompoundWidget(std::move(name),"panel"){} void RuntimeRenderTargetSection::construct(){ _summary=ui::text("RuntimeTargetsSummary").share(); _details=ui::text("RuntimeTargetsDetails").share(); auto rows=ui::column("RuntimeTargetsRows").setSpacing(3.0f).child(ui::text("RuntimeTargetsHeader").setText("Render Targets").setStyleKey("text.header")).child(_summary).child(_details); addDetachedChild(rows.release()); } void RuntimeRenderTargetSection::sync(const App* app){ if(!_summary||!_details||!app)return; auto* runtime=app->getRenderServices().getRenderRuntime(); if(!runtime){_summary->setText("Render targets unavailable");_details->setText("");return;} const auto catalog=runtime->buildRenderTargetCatalog(); _summary->setText(std::format("Targets: {}",catalog.entries.size())); if(catalog.entries.empty()){_details->setText("No render targets are available");return;} std::string text; for(const auto& entry:catalog.entries){ if(!text.empty())text.push_back('\n'); text += std::format("{} | {} | {}x{} | {}{}",entry.label,ownerLabel(entry.owner),entry.extent.width,entry.extent.height,entry.bSwapChainTarget?"swapchain":"offscreen",entry.bEditable?"":" | read-only"); } _details->setText(std::move(text)); } }
