target("ya-gui-tooling")
    set_kind(ya_target_kind())
    ya_std_module("YA_GUI_API")
    add_includedirs("./include", { public = true })
    add_files("Workbench/*.cpp")
    add_headerfiles("./include/**.h", { public = true })
    add_headerfiles("Workbench/*.h")
    add_deps("ya-gui-widgets", { public = true })
    add_packages("glm", { public = true })
