target("ya-host")
    set_kind("shared")
    ya_std_module("YA_HOST_API")
    ya_tier_include("Product")
    add_files("**.cpp")
    add_headerfiles("**.h")
    add_deps("ya-render-3d", "imgui-local", "imguizmo-local", { public = true })
    add_packages("libsdl3", "glm", "nlohmann_json", "cxxopts", { public = true })
    add_packages("asio", "vulkan-memory-allocator", "glad", "lua", "sol2", "quickjs-ng", "vulkansdk")
