target("ya-render-graph")
    set_kind("shared")
    ya_std_module("YA_RENDER_GRAPH_API")
    add_includedirs("../../../..", { public = true })
    add_files("**.cpp")
    add_headerfiles("**.h")
    add_deps("ya-foundation-rhi", { public = true })
