target("ya-render-graph")
    set_kind(ya_target_kind())
    ya_std_module("YA_RENDER_GRAPH_API")
    ya_tier_include("Render")
    add_files("**.cpp")
    add_headerfiles("**.h")
    add_deps("ya-rhi", { public = true })
