target("ya-foundation-core")
    set_kind(ya_target_kind())
    ya_std_module("YA_CORE_API")
    ya_tier_include("Foundation")
    add_includedirs("./include", { public = true })
    add_files("**.cpp")
    add_headerfiles("./include/**.h", { public = true })
    add_headerfiles("**.h")
    add_deps("utility.cc", "log.cc", "reflects-core", { public = true })
    add_packages("glm", "nlohmann_json", "libsdl3", { public = true })
