#pragma once

#include "Core/Api.h"
#include "ECS/Linkage/LinkageRule.h"
#include "Render3D/Common/RenderFeatures.h"
#include "Scene3D/CompanionRegistry.h"

#include <functional>
#include <unordered_set>

namespace ya
{

class LinkageFramework;
struct Entity;
struct Scene;

/// The single kind -> draw-feature mapping. Authored content draws as `Game`,
/// editor companions draw as `Gizmo`.
[[nodiscard]] constexpr FRenderFeatureMask renderFeatureMaskOf(ECompanionKind kind)
{
    switch (kind) {
    case ECompanionKind::EditorGizmo:
        return toMask(ERenderFeature::Gizmo);
    case ECompanionKind::Content:
        break;
    }
    return toMask(ERenderFeature::Game);
}

/// Companion lifecycle plus the single query entry point for companions.
///
/// One rule drives every declared host type: on scene init it connects the
/// hosts' entt signals and sweeps hosts that already exist (companions are
/// never serialized, so the sweep is what rebuilds them after a load), then
/// keeps exactly one generated companion entity alive for as long as the host
/// component is present.
///
/// Consumers ask this manager instead of testing component fields: provenance,
/// editability and packing class come from the host type's CompanionSpec
/// declaration, never from an asset path, entity name or field value.
struct YA_RENDER_ECS_ADAPTERS_API CompanionManager : public ILinkageRule
{
    explicit CompanionManager(LinkageFramework* framework);
    ~CompanionManager() override;

    /// Declare the companion boundary of one host component type. Called from
    /// the composition root before the rule meets a scene.
    template <typename THost>
    void declareHost(CompanionSpec spec)
    {
        CompanionRegistry::get().declare(type_index_v<THost>,
                                        std::move(spec),
                                        &presentImpl<THost>,
                                        &wireImpl<THost>,
                                        &sweepImpl<THost>);
    }

    void onSceneInit(Scene* scene) override;
    void onComponentRemoved(entt::registry& reg, entt::entity entity, ya::type_index_t type) override;
    void onSceneUnload(Scene* scene) override;

    /// entt host-component signal handler (construct / update / destroy).
    void onHostSignal(entt::registry& reg, entt::entity entity);
    /// entt transform signal handler; refreshes only declared hosts.
    void onTransformSignal(entt::registry& reg, entt::entity entity);

    // === Queries: every consumer's entry point =============================

    /// Host entity that generated `companion`; nullptr for authored entities.
    [[nodiscard]] static Entity* hostOf(const Entity& companion);
    /// True when the entity was generated by a host system.
    [[nodiscard]] static bool isGeneratedCompanion(const Entity& entity);
    /// Declared kind; undeclared companions and authored entities read as
    /// `Content` (model mesh children stay ordinary content).
    [[nodiscard]] static ECompanionKind kindOf(const Entity& entity);
    /// Whether the editor may edit this entity. Undeclared companions default
    /// to true so model mesh children keep their transform editing.
    [[nodiscard]] static bool isAuthorEditable(const Entity& entity);
    [[nodiscard]] static EAssetPackClass packClassOf(const Entity& entity);
    /// Feature bits this entity's draw items carry; `Game` for authored
    /// content, `Gizmo` for editor companions.
    [[nodiscard]] static FRenderFeatureMask featureMaskOf(const Entity& entity);
    /// Host handle for view exclusion (a camera preview view must not draw its
    /// own body); 0 for authored entities, which no view excludes.
    [[nodiscard]] static uint32_t hostEntityIdOf(const Entity& entity);
    /// The companion currently generated for `host`, or nullptr.
    [[nodiscard]] static Entity* findCompanion(Scene& scene, Entity& host);
    /// Enumerate generated companions with their declared pack class (the
    /// seam a future pack filter reads).
    static void eachCompanion(Scene&                       scene,
                              const std::function<void(Entity& companion, EAssetPackClass packClass)>& visitor);

    /// Reconcile `entity` now instead of on the deferred queue. The host
    /// signals are the production path; automation and tests use this when the
    /// companion has to exist at a known point rather than next frame.
    static void reconcileNow(Scene& scene, entt::entity entity);

  private:
    template <typename THost>
    static bool presentImpl(const entt::registry& reg, entt::entity entity)
    {
        return reg.all_of<THost>(entity);
    }

    template <typename THost>
    static void wireImpl(entt::registry& reg, CompanionManager& manager, bool bConnect);

    template <typename THost>
    static void sweepImpl(entt::registry& reg, CompanionManager& manager);

    /// Bring `entity`'s companion in line with which declared host components
    /// it currently carries. Static: the deferred task must not depend on this
    /// rule staying alive.
    static void reconcileScene(Scene& scene, entt::entity entity);
    void        scheduleReconcile(entt::registry& reg, entt::entity entity);
    void        disconnectScene(entt::registry& reg);

    /// Declared host types present on `entity`, in declaration order.
    [[nodiscard]] static std::vector<const CompanionSpec*> activeSpecs(const entt::registry& reg, entt::entity entity);
    [[nodiscard]] static const CompanionSpec*              activeSpec(const entt::registry& reg, entt::entity entity);

    LinkageFramework* _framework = nullptr;
    /// Registries this rule wired host signals on; used to disconnect on scene
    /// unload and when the rule dies before scene teardown.
    std::unordered_set<entt::registry*> _connectedRegistries;
    /// Registries that also got transform signals (declared `bFollowsHostTransform`).
    std::unordered_set<entt::registry*> _transformRegistries;
};

} // namespace ya

#include "CompanionManager.inl"
